language: node_js

matrix:
  include:
    - os: linux
    - os: osx

node_js:
  - node

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake automake libtool pkg-config; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libx11-dev libxtst-dev libxt-dev libx11-xcb-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libxkbcommon-dev libxkbcommon-x11-dev; fi
  - git submodule update --init --recursive
  
install:
  - npm i --ignore-scripts
  
script: 
  - npm run deploy

addons:
  apt:
    packages:
    - cmake
    - libx11-dev
    - libxtst-dev
    - libxt-dev
    - libx11-xcb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev